/**
 * UI utilities module exports.
 *
 * @module ui/utils
 */

export {
  createElement,
  createTextNode,
  appendChild,
  appendChildren,
  removeChild,
  removeAllChildren,
  replaceChildren,
  insertBefore,
  addClass,
  removeClass,
  toggleClass,
  hasClass,
  setClasses,
  setAttribute,
  getAttribute,
  removeAttribute,
  setDataAttribute,
  getDataAttribute,
  setStyle,
  removeStyle,
  show,
  hide,
  isVisible,
  getById,
  query,
  queryAll,
  getInputValue,
  setInputValue,
  getSelectValue,
  setSelectValue,
  getNumericValue,
  getIntegerValue,
  focus,
  blur,
  createTableRow,
  createTableRowWithElements,
  updateTableCell,
  type ElementAttributes,
  type EventHandlers,
} from './dom.js';

export {
  formatPrice,
  formatPriceWithSign,
  formatBidAsk,
  formatSpread,
  formatQuantity,
  formatQuantityWithSign,
  formatQuantityCompact,
  formatPnl,
  formatPnlClass,
  formatPnlPercent,
  formatSide,
  formatSideShort,
  formatSideClass,
  formatOrderStatus,
  formatOrderStatusClass,
  formatConnectionStatus,
  formatConnectionStatusClass,
  formatTime,
  formatTimeWithMillis,
  formatDate,
  formatDateTime,
  formatRelativeTime,
  formatSymbol,
  formatCodec,
  parsePrice,
  parseQuantity,
  parseSymbol,
} from './format.js';
